### ISSUE TITLE
Looking for maintainers?

### ISSUE THREAD

**Issue by mbbroberg** [klaudiosinani/tusk#289]
Hey @klaussinani, this project is an absolute godsend as I transition to Linux. 

It looks like this is no longer something you have time to maintain, and that's no worries - you've given a great bit of code here that I hope others can pitch in to help support. 

In the meantime, it'd be great to know how you are feeling about the project and whether you could be game to pass keys to well-meaning people to keep it going.

A note to others: If you're a well-meaning potential maintainer, comment or :+1: here!

**Comment by sfjohansson** [comment]
I agree, this has been amazing for Linux and made me start to use Evernote again as a cross-platform note-taking app, sad to see that it is not actively developed for the time being.

**Comment by Amandaville** [comment]
@klaussinani hasn't replied to any messages here a very very long time.  I think rather than wait for a reply from him, perhaps someone with the skills to maintain it could simply fork it and continue the project.  Just make sure you come back here and let the rest of us know which fork to start following.  Tusk is one of my mission-critical applications that is always running on my desktop.  The day will come when Evernote makes a change that will ultimately break Tusk and I hope someone will have stepped up by then to keep it going.  I would offer to do so if I had the coding skills.

**Comment by brooksvb** [comment]
Any updates on a fork or alternative? I've only recently started on Evernote, and there is recent news that they are building their own officially-supported linux client. But until then, I NEED something. I'll see how well this holds me over for now.

**Comment by mbbroberg** [comment]
@brooksvb I've been talking to a few people... nothing off the ground just yet. 

In the meantime, all users will have to get their hands a little dirty and keep running Tusk. You may need to build from source off a PR with fixes, but I've been running it on Fedora and Pop!_OS without much of an issue. 

There's still plenty of community around the project as visible in this issue. Open new issues to ask questions and we'll help each other keep things running.
